### ISSUE TITLE
Add 2024 Chevrolet Blazer EV

### ISSUE THREAD

**Issue by Tokigif** [Ben-Chapman/EVFinder#103]
**Manufacturer**
Chevrolet

**Vehicle Model**
2024 Blazer EV

**Link to the manufacturer's inventory webpage**
https://www.chevroletofpuentehills.com/VehicleDetails/new-2024-Chevrolet-Blazer_EV-RS_eAWD-CITY_OF_INDUSTRY-CA/5666159610

**Comment by Ben-Chapman** [comment]
Hey @Tokigif, thanks for opening this issue.

Adding these new EVs was quick, so I just shipped a new app version which includes the [2024 Blazer](https://theevfinder.com/?y=2024&m=Blazer%20EV&z=91748&r=25), Equinox and Silverado. You should be able to pick up the new app version with a page refresh (or just a new tab to [theevfinder.com](https://theevfinder.com))

The bad news is, I'm not seeing any inventory for these new EVs in the Chevrolet inventory system so you won't see any on the site.

For some reason, that dealer website has inventory which is [not appearing on Chevrolet.com](https://www.chevrolet.com/electric/shopping/inventory/search?cash=60000&dealerId&downPayment=2500&emi=650&model=Bolt%20EUV&paymentType=CASH&q-sourcepath=%2Fvdccollections%2F2023%2Fsuvs%2Fdummy-bolteuv%2Feuv%2Fjcr%3Acontent%2FvdcVehicleInfoBlockConfig%2FvdcShoppingLinks&radius=95&sortField=distance&sortOrder=ASC&x-symbolic=lnv&year=2023&zipCode=91748), which is what the EV Finder uses to display inventory results. When Blazer inventory shows up in the Chevrolet inventory systems, it'll show up on the site.

I'll keep this issue open until I start to see inventory appear.

**Comment by Ben-Chapman** [comment]
I'm starting to see inventory for 2024 Blazers in the [NYC area](https://theevfinder.com/?y=2024&m=Blazer%20EV&z=10011&r=250), around [Chicago](https://theevfinder.com/?y=2024&m=Blazer%20EV&z=60007&r=250
) and [Seattle](https://theevfinder.com/?y=2024&m=Blazer%20EV&z=98101&r=250), but none yet in California ¯\_(ツ)_/¯

I'll close this issue as completed, feel free to re-open if you're seeing issues.
