### ISSUE TITLE
Kia EV9 Request

### ISSUE THREAD

**Issue by fiehlsport** [Ben-Chapman/EVFinder#113]
**Manufacturer**
Kia

**Vehicle Model**
EV9

**Link to the manufacturer's inventory webpage**
https://www.kia.com/us/en/inventory/result?seriesId=P&year=2024&zipCode=92708&radius=50

Thank you!

**Comment by Ben-Chapman** [comment]
hey @fiehlsport, 👍🏻 thanks for the report. Adding support for the EV9 was straightforward (#114), and this was just released in [1.23.0](https://github.com/Ben-Chapman/EVFinder/releases/tag/v1.23.0).

You should see this live on the EVFinder shortly.

**Comment by fiehlsport** [comment]
Looks like it’s working great - thanks so much!

**Comment by Ben-Chapman** [comment]
Awesome, enjoy!
