### ISSUE TITLE
Where to get started?

### ISSUE THREAD

**Issue by djibouti33** [Ben-Chapman/EVFinder#31]
Great resource Ben! Apologies for opening a Github Issue but not sure how else to ask "what do you need the most help with"? Seems like the obvious improvements would be to add support for more manufacturers, but not sure if the same inventory endpoints are available for Ford, Toyota, Nissan, etc.

**Comment by Ben-Chapman** [comment]
Hey @djibouti33 
Thanks for reaching out. I'm still in the (slow) process of creating documentation, etc which should make contributing much easier. But for now, you're right - adding additional manufacturers is the highest value work. I'm working on Ford now, but help with other manufactures would be appreciated.

In the next couple of days, I'll work on:

- Documentation for the overall architecture of the site
- Documentation for adding new manufacturers 
- A list of bugs/feature requests, both to formally document them and provide a place for contributors to see what work is outstanding.

I'll comment back when I have this completed and you can take a look to see if there's anything you're interested in helping with. If you wanted to get started with adding a new manufacturer, you'll have to basically reverse engineer their inventory API(s) to obtain inventory results for a given zip code and search radius in JSON format. That work entails a lot of HTTP sniffing in dev tools, Charles, Proxyman, etc to figure out the manufacturers public inventory API. You can find the existing code examples [here](https://github.com/Ben-Chapman/EVFinder/tree/main/api/src/blueprints). As for which manufacturer to add to the site next,  ¯\_(ツ)_/¯. I suppose the priority order should be manufacturers with the greatest demand. Maybe start with Toyota?

**Comment by Ben-Chapman** [comment]
I finally got around to populating the open issues for this project. Take a look and see if there's something you're interested in and have time to help out with.
