### ISSUE TITLE
Add filter for dealer price

### ISSUE THREAD

**Issue by diegosolano** [Ben-Chapman/EVFinder#57]
Add a top-level filter for limiting dealer price as some/most dealers add a markup based on supply/demand (ex: Ioniq 5)

**Comment by Ben-Chapman** [comment]
Hey @diegosolano,
Thanks for sending this in. There's an MSRP filter in place today, which allows you to set a max dollar amount and filters the vehicle list appropriately. I plan to change the UX for that filter, replacing the slider with a min/max text input field - but the existing filter functions.

How do you envision this new filter working and/or what would be the input(s) to the proposed filter?

**Comment by LongIslandEVs** [comment]
@diegosolano 

It is near impossible to calculate markup consistently, as each dealer upcharges differently. To keep the information consistent, MSRP makes more sense.

If you'd like to see another project that is crowdsourcing Dealership markup, please see the link below.
https://datastudio.google.com/u/0/reporting/7a243d54-2a8d-44f3-a405-ce2a509c1c07/page/3KHiC
