### ISSUE TITLE
VW results only return AWD models

### ISSUE THREAD

**Issue by joesc1** [Ben-Chapman/EVFinder#76]
The results for the VW ID4 only shows results for AWD models. There are many RWD models at dealers already. Is there a filter for the VW results?

**Comment by Ben-Chapman** [comment]
Hey @joesc1,
Thanks for the report. I am seeing RWD models being shown, but the RWDs are few and far between. For example, there's [1 RWD ID.4](https://theevfinder.com/?y=2023&m=ID.4&z=10011&r=500&dri=RWD) within 500 miles of NYC. Spot checking, I've not been able to find another in the US.

If you're seeing something different on the vw.com site please let me know and I'll take a look.

I did find a bug though, it looks like the maximum number of inventory results returned for a large search area is 500 vehicles. I'll get that fixed up soon.

**Comment by Ben-Chapman** [comment]
I just fixed the 500 vehicles inventory limit and actually, found [one more RWD](https://theevfinder.com/?y=2023&m=ID.4&z=95401&r=100&dri=RWD) in California :)

**Comment by joesc1** [comment]
Thanks. Not sure where you are pulling the inventory data from, but if you look at any dealer site, there are lots of RWD vehicles in inventory. Unless there is something that is removing vehicles that were shipped as reservation fulfillment. From anecdotal reports though, there's a lot of cancellations. Here's an example of a dealer that says it has lots.  https://www.stevenscreekvw.com/new-vehicles/?q=Rwd&_dFR%5Bmake%5D%5B0%5D=Volkswagen&_dFR%5Bmodel%5D%5B0%5D=ID.4&_dFR%5Btype%5D%5B0%5D=New&_dFR%5Byear%5D%5B0%5D=2023&_paymentType=our_price

The vehicles where they say "call for price" are actually cancellations that are available.
________________________________

**Comment by joesc1** [comment]
It looks like the vw.com site doesn't show correct inventory. I just checked there, and see the same thing you do, only 1 in CA. So looks like the VW corporate inventory isn't correct. That's a bummer, but not much you can do.
