### ISSUE TITLE
Please add BMW EVs

### ISSUE THREAD

**Issue by n8gray** [Ben-Chapman/EVFinder#83]
It would be great to be able to find BMW i4 stock locally.

Thanks for the awesome resource!

**Comment by Ben-Chapman** [comment]
Hey, thanks for the request. I'm working on some behind the scenes cleanup to make the site faster and more reliable. I expect that to be finished this week, and I'll take a look at adding support for BMW BEVs shortly thereafter.

**Comment by Ben-Chapman** [comment]
Apologies for the delay, it's taken longer than I anticipated to start work this. WIP in https://github.com/Ben-Chapman/EVFinder/compare/bmw?expand=1

**Comment by Ben-Chapman** [comment]
I just shipped support for BMW EVs in [v1.17.0](https://github.com/Ben-Chapman/EVFinder/releases/tag/v1.17.0), so you should now see it live on the site. If you have any issues please let me know.

**Comment by n8gray** [comment]
This is awesome, thank you!
