### ISSUE TITLE
Support for non-HV

### ISSUE THREAD

**Issue by ndominato** [Ben-Chapman/EVFinder#97]
Hey Ben,

Messaged you on reddit but looks like you're not super active there so posting here for you as well (sorry for the stalking in advance). 

I came across the EV finder today, what an awesome site! I have my own project called AutoBolt (decodes a windshield from a VIN) and I'm trying to get an inventory feed for new vehicles. Would you be open to opening up your service to non-EV/high voltage vehicles? I'm happy to pay for this as a commercial service.

Thanks,
Nick Dominato

**Comment by Ben-Chapman** [comment]
hey @ndominato - so sorry for missing this 😞 not sure what happened there.

Thanks for the offer, but I plan to keep this EV focused and directly in support of the EV Finder. The EVFinder API is using the publicly available inventory APIs for each manufacturer, and I've designed it to be as lightweight on the manufacturer APIs as possible. By exposing this API to more public use, it's obviously harder to control how people are using it. Plus I would need to deal with all the API management chores which come with running a public API.

That said, Edmunds and Cars.com (and likely others) appear to have commercial vehicle inventory APIs which might be a better choice for what you're looking for.

I hope this helps.

**Comment by ndominato** [comment]
Hey Ben,

Not sure if replying to this email will get to you, but that does help.
Thanks for the info and your response.

Nick

**Comment by Ben-Chapman** [comment]
No problem and best of luck.
